### ISSUE TITLE
Configuration cache state could not be cached

### ISSUE THREAD

**Issue by sschuberth** [gradlex-org/jvm-dependency-conflict-resolution#157] opened 2024-08-27 10:55 UTC
With version 2.1.2 of the `org.gradlex.jvm-dependency-conflict-detection` plugin running on Gradle 8.10 and Kotlin 2.0.20 I'm getting:

```
* What went wrong:
Configuration cache state could not be cached: field `provider` of `org.gradle.internal.serialize.codecs.core.ProviderBackedFileCollectionSpec` bean found in field `element` of `java.util.Collections$SingletonList` bean found in field `elements` of `org.gradle.internal.serialize.codecs.core.ResolutionBackedFileCollectionSpec` bean found in field `__classpathSnapshot__` of `org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ClasspathSnapshotProperties` bean found in field `__classpathSnapshotProperties__` of task `:notifier:compileKotlin` of type `org.jetbrains.kotlin.gradle.tasks.KotlinCompile`: error writing value of type 'org.gradle.api.internal.provider.DefaultProvider'
```

**Comment by jjohannes** [comment] 2024-09-02 11:12
The error looks like something that is happening in the Kotlin plugin. Can you please provide a reproducer?

This – https://github.com/jjohannes/gradle-project-setup-howto/tree/kotlin – is a project with:
- Configuration Cache enabled
- latest version of `jvm-dependency-conflict-resolution` plugin
- version `2.0.20` of Kotlin plugin
- (Gradle version is 8.10)

I do not get any errors in that project.

**Comment by sschuberth** [comment] 2024-09-02 11:50
When I created this, I was able to reproduce the issue with https://github.com/oss-review-toolkit/ort/tree/jvm-dependency-conflict-resolution and running `./gradlew assemble` (I believe). However, when I just tried again, I cannot reproduce this anymore. But maybe that's just because of some cached result being reused on my end?

**Comment by jjohannes** [comment] 2024-09-06 13:07
Alright. I am closing this issue. Feel free to comment again or open a new issue if you have a reproducer that indicates that there is a problem in this plugin.

**Closed by jjohannes** 2024-09-06 13:07 UTC
